// <auto-generated />
namespace EFCodeFirstApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class modifiedemployeeclass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifiedemployeeclass));
        
        string IMigrationMetadata.Id
        {
            get { return "201806142320483_modifiedemployeeclass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
